### ISSUE TITLE
Add JPMS module name or descriptor

### ISSUE THREAD

**Issue by Marcono1234** [palantir/javapoet#53]
## What happened?

For the Java Platform Module System, square/javapoet defines an `Automatic-Module-Name` (see [`pom.xml` config](https://github.com/square/javapoet/blob/e7429cba4323e6e14d814b40833d9a9b4904cefb/pom.xml#L151)).

It looks like this fork here neither defines an `Automatic-Module-Name`, nor does it have a `module-info.class`. This makes it difficult to use in a modular project.

## What did you want to happen?

This project should either define an `Automatic-Module-Name` in the manifest, or contain a `module-info.class` (respectively `META-INF/versions/9/module-info.class` and in manifest `Multi-Release: true`).

**Comment by skku-daniilkim** [comment]
I think the project should at least just follow the way the original repo did, and simply define the "Automatic-Module-Name" in the pom/gradle:
```gradle
ext.moduleName = "com.palantir.javapoet"

jar {
    inputs.property("moduleName", moduleName)

    manifest {
       attributes  'Automatic-Module-Name': moduleName
   }
}
````

**Comment by skku-daniilkim** [comment]
I would like to provide the PR, but I am not sure, which "build.gradle" should be used. Is it the one inside the "javapoet" folder or the root one?

**Comment by carterkozak** [comment]
I believe it would go into this one: https://github.com/palantir/javapoet/blob/develop/javapoet/build.gradle

**Comment by skku-daniilkim** [comment]
Submitted a PR. It now adds the entry into the manifest properly:
![image](https://github.com/user-attachments/assets/1dfaa7b3-40c9-42b1-bd55-80d4ec9d668a)
Although I am not sure whether this will work, when built as an artifact for maven. Due to the unfamiliar build system ("gradlew build" builds two jar files: empty root jar file and the "javapoet" jar file), I only tested by building locally and linking to my other gradle project, and it seems to work with the actual "javapoet" jar file, and considering that the root jar file is literally empty, I'm pretty sure that the "build.gradle" that you mentioned is the correct one, so it should be fine.

**Comment by carterkozak** [comment]
Thanks for the contribution! I expect it to work, but you should be able to merge within ~10 minutes or so when the artifact hits maven central :-)

**Comment by skku-daniilkim** [comment]
0.4.0 just hit the central; `requires com.palantir.javapoet;` in `module-info` now works properly, and the imports work as intended with JPMS projects without any warnings.
